### ISSUE TITLE
INF Energies in 7.5.0

### ISSUE THREAD

**Issue by SimonBoothroyd** [openmm/openmm#3029]
Part of a workflow I am running involves re-evaluating the energies of a set of configurations using a different `System` definition than was originally used to generate the trajectory. With version `7.5.0` (conda-forge) I've started to see that the energies of some of the configurations are `inf`, while if I perform the same evaluations with `7.4.2` (omnia) I see real valued energies as expected.

Some caveats:

* This *only* happens when running using a `CUDA` platform - running `7.5.0` with the `CPU` and `Reference` platform yields real valued energies which also match the `7.4.2` CPU energies.
* This only happens when evaluating the energies of multiple conformers in sequence. If I evaluate the energy of the conformer which yields an `inf` energy by itself then it returns a real valued energy.

I have attached a simple reproduction case. 

[inf-energy-7-4-2.tar.gz](https://github.com/openmm/openmm/files/6028354/inf-energy-7-4-2.tar.gz)
[inf-energy-7-5-0.tar.gz](https://github.com/openmm/openmm/files/6028356/inf-energy-7-5-0.tar.gz)

The two sets of files are nearly identical except for the `openmmVersion` line in the `system.xml` files and the addition of `exceptionsUsePeriodic="0"` to the non-bonded force section for the `7.5.0` version.

I run `inf-energy-7-4-2.tar.gz` using a conda environment created by running

```
conda create --name openmm-7-4-2 -c conda-forge -c omnia "omnia::openmm" mdtraj
```

and `inf-energy-7-5-0.tar.gz` using a conda environment created by running

```
conda create --name openmm-7-5-0 -c conda-forge openmm mdtraj
```

Line `8` of `run.py` can be altered to either evaluate configurations from the full trajectory (`[0:11]`), for the configuration which has `inf` energy in `7.5.0` (`[10:11]`), or for a subset of configurations (`[1:11]`). I only see `inf` energies when evaluating the full trajectory.

I ran the repro cases on a `GeForce RTX 2080` with `cuda/10.1`. The header of running `nvidia-smi` looks like:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
```

When running with `7.4.2` I get an output of:

```
-14256.628503305676 kJ/mol
-14623.87380296432 kJ/mol
-14226.208971641317 kJ/mol
-14250.353767193057 kJ/mol
-14331.184504272273 kJ/mol
-14332.873993503317 kJ/mol
-13987.614458549313 kJ/mol
-14044.734625616733 kJ/mol
-14063.66333731304 kJ/mol
-13935.28054184882 kJ/mol
-14343.641661601061 kJ/mol
```

and with `7.5.0`:

```
-14256.628503305676 kJ/mol
-14623.87380296432 kJ/mol
-14226.20897164132 kJ/mol
-14250.353767193057 kJ/mol
-14331.184504272273 kJ/mol
-14332.873993503317 kJ/mol
-13987.614458549315 kJ/mol
-14044.734625616735 kJ/mol
-14063.66333731304 kJ/mol
-13935.280541848819 kJ/mol
inf kJ/mol
```

**Comment by dotsdl** [comment]
Thank you @SimonBoothroyd! I can confirm reproduction of this issue.

Using 7.4.2 with CUDA 11.2.1 (Arch Linux community package), I get:
```
-14256.628503305677 kJ/mol
-14623.87380296432 kJ/mol
-14226.20897164132 kJ/mol
-14250.353767193057 kJ/mol
-14331.184504272273 kJ/mol
-14332.873993503317 kJ/mol
-13987.614458549313 kJ/mol
-14044.734625616735 kJ/mol
-14063.66333731304 kJ/mol
-13935.28054184882 kJ/mol
-14343.641661601061 kJ/mol
```

Using 7.5.0 with `conda-forge::cudatoolkit` version `11.2.1`:

```
-14256.628503305676 kJ/mol
-14623.873802964321 kJ/mol
-14226.20897164132 kJ/mol
-14250.353767193057 kJ/mol
-14331.184504272273 kJ/mol
-14332.873993503317 kJ/mol
-13987.614458549315 kJ/mol
-14044.734625616735 kJ/mol
-14063.66333731304 kJ/mol
-13935.280541848822 kJ/mol
inf kJ/mol
```

@peastman any thoughts on what else we might try to pin down what could be happening here?

**Comment by peastman** [comment]
Here's what I get using the latest development code:

```
-14256.628503305677 kJ/mol
-14623.87380296432 kJ/mol
-14226.208971641317 kJ/mol
-14250.353767193057 kJ/mol
-14331.184504272273 kJ/mol
-14332.873993503317 kJ/mol
-13987.614458549313 kJ/mol
-14044.734625616735 kJ/mol
-14063.66333731304 kJ/mol
-13935.28054184882 kJ/mol
-14343.641661601063 kJ/mol
```

I also tried running it in `cuda-memcheck`, in case this was a non-deterministic problem caused by uninitialized memory or something similar, but it didn't report any problems.

Possibly this is something that has already been fixed since 7.5.0.  Could you try the latest nightly build?

```
conda install -c omnia-dev openmm
```

I also want to clarify something.  You have two different versions of the files, and also you're testing with two different versions of OpenMM.  What happens if you mix them, such as using the "7.4.2" files in OpenMM 7.5?  Are the energies correct?

**Comment by SimonBoothroyd** [comment]
Hi @peastman - thanks for testing this! 

> I also want to clarify something. You have two different versions of the files, and also you're testing with two different versions of OpenMM. What happens if you mix them, such as using the "7.4.2" files in OpenMM 7.5? Are the energies correct?

I tried running the 7.4.2 inputs with 7.5.0 as suggested and the energy of the last configuration is still `inf`, while the other energies all match running with 7.4.2.

> Possibly this is something that has already been fixed since 7.5.0. Could you try the latest nightly build?

I tried this just now and using the nightly `openmm` build does seem to resolve the issue, so it seems like this has already been fixed in `master`. Is there a rough timeline for when you expect to make a `7.5.1` / `7.6.0` release?

**Comment by peastman** [comment]
Let me see if I can figure out what change fixed this.  We haven't scheduled the next major release yet, but there will probably be a 7.5.1 minor release soon.  Possibly we can include this.

**Comment by peastman** [comment]
It turns out the problem wasn't really fixed.  You had the bad luck to run into a *very* rare error.  A later code change happened to perturb the state of things such that it didn't come up.  The real fix is in #3057.

**Comment by SimonBoothroyd** [comment]
Thanks for hunting down and fixing this @peastman!
