### ISSUE TITLE
Kernel compilation errors on HIP 7

### ISSUE THREAD

**Issue by timpalpant** [openmm/openmm#5160]
I am attempting to run on AMD Radeon 7900 XTX and HIP 7 (Arch Linux). I receive the following error when the HIP kernel is compiled.

Repro:
```
$ conda create --override-channels -c conda-forge -n openmm python
$ conda activate openmm
$ pip install openmm[hip7]
$ python -m openmm.testInstallation
```

Output:
```
OpenMM Version: 8.4
Git Revision: 47684368dbbe4185d068be77d32a962059cfc37c

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 HIP - Error computing forces with HIP platform
3 CPU - Successfully computed forces
4 OpenCL - Successfully computed forces

HIP platform error: Error compiling program: /tmp/comgr-c63d46/input/CompileSourceMunxVy:110:10: error: no template named 'enable_if' in namespace 'std'; did you mean '__hip_internal::enable_if'?
  110 | typename std::enable_if<(Subwarp == warpSize), T>::type
      |          ^~~~~~~~~~~~~~
      |          __hip_internal::enable_if
/tmp/comgr-c63d46/include/hiprtc_runtime.h:1447:46: note: '__hip_internal::enable_if' declared here
 1447 | template <bool __B, class __T = void> struct enable_if {};
      |                                              ^
/tmp/comgr-c63d46/input/CompileSourceMunxVy:117:10: error: no template named 'enable_if' in namespace 'std'; did you mean '__hip_internal::enable_if'?
  117 | typename std::enable_if<!(Subwarp == warpSize), T>::type
      |          ^~~~~~~~~~~~~~
      |          __hip_internal::enable_if
/tmp/comgr-c63d46/include/hiprtc_runtime.h:1447:46: note: '__hip_internal::enable_if' declared here
 1447 | template <bool __B, class __T = void> struct enable_if {};
      |                                              ^
2 errors generated when compiling for gfx1100.


Median difference in forces between platforms:

Reference vs. CPU: 6.28899e-06
Reference vs. OpenCL: 6.7461e-06
CPU vs. OpenCL: 7.58122e-07

All differences are within tolerance.
```

I attempted to fix it by replacing [these sites](https://github.com/openmm/openmm/blob/master/platforms/hip/src/kernels/intrinsics.hip#L36) with `__hip_internal::enable_if`. When I did that, I ran into other errors relating to `warpSize` not being a compile-time constant. I hard-coded it to 32 and then was able to run `python -m openmm.testInstallation` successfully, but I am not sure what the correct fix is.

```
$ hipcc --version
HIP version: 7.1.52802-9999
AMD clang version 20.0.0git (/srcdest/rocm-llvm 27682a16360e33e37c4f3cc6adf9a620733f8fe1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/lib/llvm/bin
Build config: +assertions
```

**Comment by peastman** [comment]
I haven't encountered that error.  Perhaps @ex-rzr has some insight into what's causing it?

What happens if you add `#include <type_traits>` at the top of that file?  That's the header that `std::enable_if` is defined it.

**Comment by timpalpant** [comment]
Including `<type_traits>` does resolve the error pertaining to `std::enable_if`.

I still get the errors pertaining to `warpSize`:
```
HIP platform error: Error compiling program: /tmp/comgr-29b7de/input/CompileSource8mqKN6:750:19: error: constexpr variable 'tilesPerWarp' must be initialized by a constant expression
  750 |     constexpr int tilesPerWarp = warpSize/TILE_SIZE;
      |                   ^              ~~~~~~~~~~~~~~~~~~
/tmp/comgr-29b7de/input/CompileSource8mqKN6:750:34: note: non-constexpr function 'operator int' cannot be used in a constant expression
  750 |     constexpr int tilesPerWarp = warpSize/TILE_SIZE;
      |                                  ^
/tmp/comgr-29b7de/include/hiprtc_runtime.h:6409:52: note: declared here
 6409 |   __device__ __attribute__((always_inline, const)) operator int() const noexcept {
```

**Note**: I had to clear the kernel cache (in `/tmp`) to reproduce this issue after previous success.

I found these references which seem relevant:

- https://rocm.docs.amd.com/projects/HIP/en/latest/hip-7-changes.html#hip-header-clean-up

> HIP header files previously included unnecessary Standard Template Libraries (STL) headers. With the 7.0 release, unnecessary STL headers are no longer included, and only the required STL headers are included. Applications relying on HIP runtime header files might need to be updated to include STL header files that have been removed in 7.0.

- https://rocm.docs.amd.com/projects/HIP/en/latest/hip-7-changes.html#warpsize-change
- https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/hip_cpp_language_extensions.html#warpsize

> To match the CUDA specification, warpSize is no longer a constexpr. In general, this should be a transparent change. However, if an application was using warpSize as a compile-time constant, it will have to be updated to handle the new definition.

**Comment by peastman** [comment]
That explains it.  I can fix it.

**Comment by ex-rzr** [comment]
Two `constexpr` in `platforms/hip/src/kernels/findInteractingBlocks.hip` are not really needed, they can be replaced with `const`.

> Note: I had to clear the kernel cache (in /tmp) to reproduce this issue after previous success.

This is strange actually. Any changes in kernel sources causes rebuilding, as the hash is different...

**Comment by peastman** [comment]
The fix is in #5161.  @timpalpant can you test it and verify it now works for you?

**Comment by timpalpant** [comment]
> This is strange actually. Any changes in kernel sources causes rebuilding, as the hash is different...

Sorry, I must have misattributed and just not rebuilt correctly or sufficiently.

> The fix is in https://github.com/openmm/openmm/pull/5161. @timpalpant can you test it and verify it now works for you?

There are some additional errors:

```
HIP platform error: Error compiling program: /tmp/comgr-cea26e/input/CompileSource2xK6vd:757:36: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
  757 |     __shared__ int workgroupBuffer[BUFFER_SIZE*warpsPerBlock];
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:431:21: note: expanded from macro 'BUFFER_SIZE'
  431 | #define BUFFER_SIZE 256
      |                     ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:757:48: note: initializer of 'warpsPerBlock' is not a constant expression
  757 |     __shared__ int workgroupBuffer[BUFFER_SIZE*warpsPerBlock];
      |                                                ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:749:15: note: declared here
  749 |     const int warpsPerBlock = GROUP_SIZE/warpSize;
      |               ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:757:20: error: variable length array declaration cannot have 'static' storage duration
  757 |     __shared__ int workgroupBuffer[BUFFER_SIZE*warpsPerBlock];
      |                    ^               ~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:758:41: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
  758 |     __shared__ real4 workgroupPosBuffer[TILE_SIZE*warpsPerBlock];
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:112:19: note: expanded from macro 'TILE_SIZE'
  112 | #define TILE_SIZE 32
      |                   ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:758:51: note: initializer of 'warpsPerBlock' is not a constant expression
  758 |     __shared__ real4 workgroupPosBuffer[TILE_SIZE*warpsPerBlock];
      |                                                   ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:749:15: note: declared here
  749 |     const int warpsPerBlock = GROUP_SIZE/warpSize;
      |               ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:758:22: error: variable length array declaration cannot have 'static' storage duration
  758 |     __shared__ real4 workgroupPosBuffer[TILE_SIZE*warpsPerBlock];
      |                      ^                  ~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:759:40: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
  759 |     __shared__ int workgroupExclusions[MAX_EXCLUSIONS*warpsPerBlock];
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:103:24: note: expanded from macro 'MAX_EXCLUSIONS'
  103 | #define MAX_EXCLUSIONS 3
      |                        ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:759:55: note: initializer of 'warpsPerBlock' is not a constant expression
  759 |     __shared__ int workgroupExclusions[MAX_EXCLUSIONS*warpsPerBlock];
      |                                                       ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:749:15: note: declared here
  749 |     const int warpsPerBlock = GROUP_SIZE/warpSize;
      |               ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:759:20: error: variable length array declaration cannot have 'static' storage duration
  759 |     __shared__ int workgroupExclusions[MAX_EXCLUSIONS*warpsPerBlock];
      |                    ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:760:42: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
  760 |     __shared__ int workgroupBlock2Buffer[(warpSize+1)*warpsPerBlock];
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-cea26e/input/CompileSource2xK6vd:760:43: note: non-constexpr function 'operator int' cannot be used in a constant expression
  760 |     __shared__ int workgroupBlock2Buffer[(warpSize+1)*warpsPerBlock];
      |                                           ^
/tmp/comgr-cea26e/include/hiprtc_runtime.h:6409:52: note: declared here
 6409 |   __device__ __attribute__((always_inline, const)) operator int() const noexcept {
      |                                                    ^
/tmp/comgr-cea26e/input/CompileSource2xK6vd:760:20: error: variable length array declaration cannot have 'static' storage duration
  760 |     __shared__ int workgroupBlock2Buffer[(warpSize+1)*warpsPerBlock];
      |                    ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings and 4 errors generated when compiling for gfx1100.
```

**Comment by ex-rzr** [comment]
I fixed all errors in #5162 and checked on MI200 (CDNA) and RX 9070 (RDNA).

Also I encountered errors in QTB tests unrelated to this issue, I made a fix in a separate PR: #5163

**Comment by peastman** [comment]
Thanks!  @timpalpant can you verify that #5162 fixes it for you?

**Comment by timpalpant** [comment]
> Thanks! [@timpalpant](https://github.com/timpalpant) can you verify that [#5162](https://github.com/openmm/openmm/pull/5162) fixes it for you?

Yes, this branch works for me on 7900 XTX. I tested with HIP6 and HIP7. Thank you both!

**Comment by peastman** [comment]
Great, thank you both!

**Comment by supriyonaskar** [comment]
I still have this error 


OpenMM Version: 8.4
Git Revision: 47684368dbbe4185d068be77d32a962059cfc37c

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 HIP - Error computing forces with HIP platform
4 OpenCL - Successfully computed forces

HIP platform error: Error compiling program: /tmp/comgr-35a9f6/input/CompileSource1wNBod:109:10: error: no template named 'enable_if' in namespace 'std'; did you mean '__hip_internal::enable_if'?
  109 | typename std::enable_if<(Subwarp == warpSize), T>::type
      |          ^~~~~~~~~~~~~~
      |          __hip_internal::enable_if
/tmp/comgr-35a9f6/include/hiprtc_runtime.h:1447:46: note: '__hip_internal::enable_if' declared here
 1447 | template <bool __B, class __T = void> struct enable_if {};
      |                                              ^
/tmp/comgr-35a9f6/input/CompileSource1wNBod:116:10: error: no template named 'enable_if' in namespace 'std'; did you mean '__hip_internal::enable_if'?
  116 | typename std::enable_if<!(Subwarp == warpSize), T>::type
      |          ^~~~~~~~~~~~~~
      |          __hip_internal::enable_if
/tmp/comgr-35a9f6/include/hiprtc_runtime.h:1447:46: note: '__hip_internal::enable_if' declared here
 1447 | template <bool __B, class __T = void> struct enable_if {};
      |                                              ^
2 errors generated when compiling for gfx942.


**System and software**
Processor type: AMD Instinct MI300A APU

Name: OpenMM-HIP-7
Version: 8.4.0.post2
